/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     29/01/2024 20:59:03
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "HAWB_APRS_lib.h"
#include <stdlib.h>


/** Functions ----------------------------------------------------------------*/
void getLocation(I2C_HandleTypeDef* hi2c, struct Position* location) {
	uint8_t* request = malloc(sizeof(uint8_t));
	*request = 1;
	HAL_I2C_Master_Transmit(hi2c,APRS_ID,request,sizeof(uint8_t),0);
	HAL_I2C_Master_Receive(hi2c,APRS_ID,(uint8_t *)location, sizeof(struct Position),0);
	free(request);
}
