name: Doxygen

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison make g++ python3 graphviz
          mkdir vendor;
          cd vendor;
          curl https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz > doxygen-1.12.0.linux.bin.tar.gz
          gunzip doxygen-1.12.0.linux.bin.tar.gz    
          tar xf doxygen-1.12.0.linux.bin.tar
          sudo cp doxygen-1.12.0/bin/doxygen /usr/local/bin/doxygen

      - name: Generate documentations
        run: |
          doxygen ./config/Doxyfile
          ls docs/html
